AWS_ACCESS_KEY_ID = "AKIA42LW7ORTOGK2SGYF"
AWS_SECRET_ACCESS_KEY = "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"
BUCKET = "deepaa-algo-trade"
KEY = "web_data/user_details.json"
REGION = "ap-south-1"
APP_PASSWORD = "Deepa123!"
